services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS zeeguu_test;" -uroot
  - mysql -e "grant all on zeeguu_test.* to 'zeeguu_test'@'localhost' identified by 'zeeguu_test';" -uroot
  - mkdir -p ~/.config/zeeguu/ && cp default_api.cfg ~/.config/zeeguu/api_testing.cfg
  - pip install jieba3k
  - pip install coveralls
  - pip install nltk
  - python -m nltk.downloader -d ~/nltk_data all


language: python
python:
  - "3.6"

cache:
  pip: true

install: "python setup.py develop"

script: 
  - "./run_tests.sh"
  - "export DASHBOARD_CONFIG=/home/travis/build/kloostert/Zeeguu-API/dashboard_test.cfg"
  - "export DASHBOARD_LOG_DIR=/home/travis/build/kloostert/Zeeguu-API/"
  - "python -m dashboard.collect_performance"
