before_install:
  - pip install -r https://raw.githubusercontent.com/zeeguu-ecosystem/Zeeguu-Core/master/requirements.txt
  - python -m nltk.downloader -d ~/nltk_data punkt
  - pip install -r requirements.txt

language: python
python:
  - "3.6"

cache:
  pip: true

install: "python setup.py develop"

script: 
  - "./run_tests.sh"
  #- "python -m flask_monitoringdashboard.collect_performance --test_folder ./tests_zeeguu_api/ --url https://zeeguu.unibe.ch/api/dashboard"

