name: Render ARchitectural Diff with ArchLens

on:
  workflow_dispatch:

jobs:
  render-diff-and-upload-comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: run_archlens
        uses: archlens/render-diff-on-pr@main
        with:
          config-path: "archlens.json"
          render-diff: "true"
          BRANCH_NAME: "_archlens_diff"
